# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-01 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '《漂亮女医生的风雨爱情》',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '医科圣手',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '召唤狂人在异界',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '天门鬼道',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '女仆的异界传说',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '少将的纯情宝贝',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '巾帼娇',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '御道',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '战帝',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '护花狂尸',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '拳灭天穹',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '万能高手',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '无限进化',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '权路',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '极品司机',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '极度尸寒',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '校园妙手神医',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '校花的极品高手',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '校花的近身高手',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '武侠重生',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '武极乾坤',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S29',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '猎巫之王',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '上古神王',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '电影中的兑换强者',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S31',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '秋叶原之魔鬼经纪人',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '纯情花嫁',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S33',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '职场小白升职记',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S34',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '背后高手',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S35',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '越狱红莲：邻家小妹是恶魔',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S36',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '足球豪门',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S37',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '都市女秘书',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '重生之名门千金',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S39',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '重生之嫡非良善',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '不朽音魔',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '野蛮女友',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S41',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '阴阳手眼',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S42',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '隐宠爱妻',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S43',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '霉妃瑟舞',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S44',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '霸情冷少，勿靠近',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S45',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '霸情恶少：调教小逃妻',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S46',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '霸气宝宝：带着娘亲闯江湖',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S47',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '霸道首席毒宠美妻',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S48',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '青春的死胡同',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S49',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '魔手系统',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '九界无仙',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S50',
            fields=[
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '黄金渔场',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '任性老婆好V5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '傲世圣灵',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '兽血沸腾',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '凤求凰',
                'managed': False,
            },
        ),
    ]
